Neos:
  Neos:
    modules:
      administration:
        submodules:
          nodetypes:
            label: 'Nodetypes Analyzer'
            controller: 'Shel\ContentRepository\Debugger\Controller\NodeTypesController'
            description: 'Shel.ContentRepository.Debugger:Main:module.description'
            icon: fas fa-sitemap
            privilegeTarget: 'Shel.ContentRepository.Debugger:Backend.Module.Administration.NodeTypes'
            additionalResources:
              styleSheets:
                - 'resource://Shel.ContentRepository.Debugger/Public/Styles/main.css'
              javaScripts:
                - 'resource://Shel.ContentRepository.Debugger/Public/JavaScript/main.bundle.js'
