Neos:
  Neos:
    modules:
      administration:
        submodules:
          nodetypes:
            label: 'Nodetypes Analyzer'
            controller: 'Shel\ContentRepository\Debugger\Controller\NodeTypesController'
            description: 'Shel.ContentRepository.Debugger:Main:module.description'
            icon: fas fa-sitemap
            privilegeTarget: 'Shel.ContentRepository.Debugger:Backend.Module.Administration.NodeTypes'
            additionalResources:
              javaScripts:
                - 'resource://Shel.ContentRepository.Debugger/Public/Assets/main.bundle.js'
              styleSheets:
                - 'resource://Shel.ContentRepository.Debugger/Public/Assets/extra-neos-wrapper.css'
                - 'resource://Shel.ContentRepository.Debugger/Public/Assets/main.bundle.css'

Shel:
  ContentRepository:
    Debugger:
      defaults:
        graphviz:
          graph:
            rankdir: 'LR'
            pack: 'true'
            layout: 'neato'
            model: 'subset'
            splines: 'true'
            overlap: 'false'
            fontname: 'Noto Sans'

          node:
            width: '.25'
            height: '.375'
            fontsize: '11'
            fontname: 'Noto Sans'
            fillcolor: '#ffffff'
            style: 'filled'

          edge:
            color: '#888888'
